src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_update;
    
    public function __construct() {
        $this->date_update = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle(string $title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription(string $description)
    {
        $this->description = $description;

        return $this;
    }

    public function getDateUpdate()
    {
        return $this->date_update->format('d.m.Y H:i:s');
    }

    public function setDateUpdate(\DateTimeInterface $date_update)
    {
        $this->date_update = $date_update;

        return $this;
    }
}

src/Controller/Blog.php
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Post;



class Blog extends AbstractController
{    
    /**
     * @Route("/", name="list", methods={"GET"})
     */
    public function listPosts()
    {
        $em = $this->getDoctrine()->getManager();
        
        $posts = $em->getRepository(Post::class)->findAll();
                
        return $this->render('posts/list.html.twig', [
            "posts" => $posts
        ]);
    }
    
    
    /**
     * @Route("/post/edit/{id}", name="edit", methods={"GET"})
     */
    public function editPost(int $id)
    {
//        var_dump($id);
        $em = $this->getDoctrine()->getManager();
        
        $Post = $em->find(Post::class, $id);
        
        return $this->render('posts/edit.html.twig', ['post' => $Post]);
    }
    
     /**
     * @Route("/post/add", name="add", methods={"GET"})
     */
    public function addPost()
    {
        return $this->render('posts/add.html.twig');
    }
    
     /**
     * @Route("/post/save", name="save", methods={"POST"})
     */
    public function savePost()
    {
        $title = $_POST['title'];
        $description = $_POST['description']; 
        
        $em = $this->getDoctrine()->getManager();
        
        if(isset($_POST['id'])) {
            $id = $_POST['id'];
            $Post = $em->find(Post::class, $id);
            $Post->setTitle($title);
            $Post->setDescription($description);
            
            $em->persist($Post);
            $em->flush();
            
            return $this->render('posts/success_updated.html.twig');
        }
        
        $Post = new Post();
        
        $Post->setTitle($title);
        $Post->setDescription($description);
        
        $em->persist($Post);
        $em->flush();
        
        return $this->render('posts/success.html.twig');
    }
    
    /**
     * @Route("/post/{id}", name="show", methods={"GET"})
     */
    public function showPost(int $id)
    {
//        var_dump($id);
        $em = $this->getDoctrine()->getManager();
        
        $Post = $em->find(Post::class, $id);
        
        return $this->render('posts/show.html.twig',[
            "post" => $Post
        ]);
    }
    
    /**
     * @Route("/post/remove/{id}", name="remove", methods={"GET"})
     */
    public function removePost(int $id)
    {
//        var_dump($id);
        $em = $this->getDoctrine()->getManager();
        
        $Post = $em->find(Post::class, $id);
        
        $em->remove($Post);
        
        $em->flush();
        return $this->render('posts/success_remove.html.twig');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link href="/style.css" rel="stylesheet"/>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="header-wrap">
                <div class="logo">
                    Blog posts
                </div>
            </div>
        </header>
        <div class="page">
            {% block body %}{% endblock %}
        </div>
        <footer>
            posts 2020
        </footer>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/posts/add.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>Add post</h1>
    <form action="/post/save" method="POST" class="post-form">
        <label>
            Enter Title
            <input name="title" type="text" />
        </label>
        <label>
            Enter Description
            <textarea name="description"></textarea>
        </label>
        <button class="btn-blue">Create post</button>
    </form>
{% endblock %}

templates/posts/edit.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>Edit post</h1>
    <form action="/post/save" method="POST" class="post-form">
        <input type="hidden" name="id" value="{{post.id}}"/>
        <label>
            Edit Title
            <input value="{{post.title}}" name="title" type="text" />
        </label>
        <label>
            Edit Description
            <textarea name="description">{{post.description}}</textarea>
        </label>
        <button class="btn-blue">Edit post</button>
    </form>
{% endblock %}

templates/posts/list.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>List posts</h1>
    <a class="btn" href="/post/add">Add post</a>
    
    <div class="post-list">
        {% for post in posts %}
            <div class="post">
                <h3>{{post.title}}</h3>
                <i>{{post.dateUpdate}}</i>
                <a href = "/post/edit/{{post.id}}">Edit</a>
                <a href = "/post/{{post.id}}">More...</a>
                <a href = "/post/remove/{{post.id}}">Remove</a>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

templates/posts/show.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>{{post.title}}</h1>
    <a href="/">List posts</a>

    <div class="post">
        <h3>{{post.title}}</h3>
        <i>{{post.dateUpdate}}</i>
        <p>{{post.description}}</p>
        <a href = "/post/remove/{{post.id}}">Remove</a>
    </div>
    
{% endblock %}

templates/posts/success.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>Post added success</h1>
    <a class="btn" href="/">List posts</a>
{% endblock %}

templates/posts/success_remove.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>Post deleted success</h1>
    <a class="btn" href="/">List posts</a>
{% endblock %}

templates/posts/success_updated.html.twig
{% extends "base.html.twig" %}


{% block body %}
    <h1>Post updated success</h1>
    <a class="btn" href="/">List posts</a>
{% endblock %}